/**
 * Sealed-Bid Quote Service — 2.4
 *
 * Simulates vetKeys IBE (Identity-Based Encryption) sealed bidding.
 *
 * Mock mode (no canister):
 *   - "Encryption": btoa(JSON({a: amount, r: requestId}))
 *   - "Decryption": JSON.parse(atob(ciphertext)).a
 *   - All state lives in JS maps; reset() clears everything.
 *
 * Production (canister + @dfinity/vetkeys):
 *   - Contractor: IBE-encrypt amountCents with canister public key → Uint8Array ciphertext
 *   - Canister: stores ciphertext; vetkd_derive_key derives homeowner's IBE key after closeAt
 *   - Homeowner: receives encryptedKey + raw ciphertexts, decrypts locally with vetkeys SDK
 *
 * Real IBE context: "hg-bid-v1" — must match IBE_CONTEXT bytes in backend/quote/main.mo
 */

export interface SealedBidRequest {
  id:          string;
  propertyId:  string;
  homeowner:   string;   // principal text
  serviceType: string;
  description: string;
  urgency:     "low" | "medium" | "high" | "emergency";
  status:      "open" | "quoted" | "accepted" | "closed";
  createdAt:   number;   // ms
  closeAt:     number;   // ms — bid window closes at this time
}

/** A sealed bid as stored before reveal. Amount is hidden inside ciphertext. */
export interface SealedBid {
  id:           string;
  requestId:    string;
  contractor:   string;   // principal text
  ciphertext:   string;   // IBE-encrypted bid (base64 in mock)
  timelineDays: number;
  submittedAt:  number;   // ms
}

/** A bid after the homeowner triggers reveal — amount is now visible. */
export interface RevealedBid {
  id:           string;
  requestId:    string;
  contractor:   string;
  amountCents:  number;
  timelineDays: number;
  submittedAt:  number;
  isWinner:     boolean;  // true for the lowest-price bid
}

// ─── Mock IBE crypto ──────────────────────────────────────────────────────────
// In production: use @dfinity/vetkeys IBE encrypt/decrypt with canister public key.

function mockIbeEncrypt(amountCents: number, requestId: string): string {
  // Mix in requestId so same amount → different ciphertext for different requests
  return btoa(JSON.stringify({ a: amountCents, r: requestId }));
}

function mockIbeDecrypt(ciphertext: string): { amountCents: number; requestId: string } {
  let parsed: any;
  try {
    parsed = JSON.parse(atob(ciphertext));
  } catch {
    throw new Error("sealedBid: invalid ciphertext — cannot decode bid");
  }
  if (typeof parsed?.a !== "number" || typeof parsed?.r !== "string") {
    throw new Error("sealedBid: malformed bid payload");
  }
  return { amountCents: parsed.a, requestId: parsed.r };
}

// ─── Service factory ──────────────────────────────────────────────────────────

function createSealedBidService() {
  const requests            = new Map<string, SealedBidRequest>();
  const bids                = new Map<string, SealedBid>();
  const bidsByRequest       = new Map<string, string[]>();              // requestId → bidId[]
  const bidByContractor     = new Map<string, string>();                // `${contractor}:${requestId}` → bidId
  const revealedByRequest   = new Map<string, RevealedBid[]>();
  let counter = 0;

  return {
    /**
     * Create a new sealed-bid quote request with a bid-window close time.
     * The `id` field is taken from the input (caller supplies it for test predictability);
     * in production it would be generated by the canister.
     */
    createSealedBidRequest(
      req:       Omit<SealedBidRequest, "homeowner" | "status" | "createdAt">,
      homeowner  = "local",
      now        = Date.now()
    ): SealedBidRequest {
      const r: SealedBidRequest = {
        ...req,
        homeowner,
        status:    "open",
        createdAt: now,
      };
      requests.set(req.id, r);
      return r;
    },

    /** True while the bid-submission window is still open. */
    isBidWindowOpen(request: SealedBidRequest, now = Date.now()): boolean {
      return now < request.closeAt;
    },

    /**
     * Submit an encrypted (sealed) bid for a request.
     * Throws "BidWindowClosed" if the window has already closed.
     * In mock mode the ciphertext is base64(JSON({a, r})); in production it would
     * be the IBE ciphertext produced by @dfinity/vetkeys.
     */
    submitSealedBid(
      requestId:    string,
      amountCents:  number,
      timelineDays: number,
      contractor    = "local",
      now           = Date.now()
    ): SealedBid {
      const req = requests.get(requestId);
      if (req && now >= req.closeAt) {
        throw new Error(`Bid window closed for request ${requestId} — deadline was ${new Date(req.closeAt).toISOString()}`);
      }
      const ciphertext = mockIbeEncrypt(amountCents, requestId);
      const id         = `SB_${++counter}`;
      const bid: SealedBid = {
        id, requestId, contractor, ciphertext, timelineDays, submittedAt: now,
      };
      bids.set(id, bid);
      bidsByRequest.set(requestId, [...(bidsByRequest.get(requestId) ?? []), id]);
      bidByContractor.set(`${contractor}:${requestId}`, id);
      return bid;
    },

    /**
     * Returns the calling contractor's own sealed bid for a request (ciphertext only).
     * Returns undefined if the contractor has not bid on this request.
     * Contractors cannot query each other's bids — use getRevealedBids() after reveal.
     */
    getMyBid(requestId: string, contractor = "local"): SealedBid | undefined {
      const bidId = bidByContractor.get(`${contractor}:${requestId}`);
      return bidId ? bids.get(bidId) : undefined;
    },

    /**
     * Reveal all bids for a request after the bid window closes.
     * Decrypts every ciphertext in-canister (simulated in mock) and marks the
     * lowest-price bid as isWinner.
     *
     * Throws "BidWindowOpen" if called before closeAt.
     * Idempotent: calling twice returns the same result.
     */
    revealBids(
      requestId:  string,
      _requester  = "local",   // in production: canister checks caller == homeowner
      now         = Date.now()
    ): RevealedBid[] {
      const req = requests.get(requestId);
      if (req && now < req.closeAt) {
        throw new Error(`Bid window still open for request ${requestId} — closes at ${new Date(req.closeAt).toISOString()}. Call revealBids() only after the deadline.`);
      }
      const cached = revealedByRequest.get(requestId);
      if (cached) return cached;

      const bidIds = bidsByRequest.get(requestId) ?? [];
      const decoded = bidIds
        .map((id) => bids.get(id)!)
        .filter(Boolean)
        .map((b) => ({ bid: b, amountCents: mockIbeDecrypt(b.ciphertext).amountCents }));

      const minAmount = Math.min(...decoded.map((d) => d.amountCents));
      const revealed: RevealedBid[] = decoded.map(({ bid, amountCents }) => ({
        id:           bid.id,
        requestId:    bid.requestId,
        contractor:   bid.contractor,
        amountCents,
        timelineDays: bid.timelineDays,
        submittedAt:  bid.submittedAt,
        isWinner:     amountCents === minAmount,
      }));

      revealedByRequest.set(requestId, revealed);
      return revealed;
    },

    /** Returns already-revealed bids, or an empty array if reveal has not been called yet. */
    getRevealedBids(requestId: string): RevealedBid[] {
      return revealedByRequest.get(requestId) ?? [];
    },

    /** Returns the winning (lowest-price) RevealedBid, or undefined if not yet revealed. */
    getWinner(requestId: string): RevealedBid | undefined {
      return this.getRevealedBids(requestId).find((b) => b.isWinner);
    },

    reset() {
      requests.clear();
      bids.clear();
      bidsByRequest.clear();
      bidByContractor.clear();
      revealedByRequest.clear();
      counter = 0;
    },
  };
}

export const sealedBidService = createSealedBidService();

// ─── Real IBE crypto utilities (production) ───────────────────────────────────
// These functions use @dfinity/vetkeys and are called by quoteService methods
// when a real canister is available.  Unit tests use the mock service above.

/** Encode amountCents as a 4-byte little-endian Uint8Array. */
function encodeAmountCents(amountCents: number): Uint8Array {
  const buf = new Uint8Array(4);
  let n = amountCents >>> 0;   // treat as unsigned 32-bit
  buf[0] = n & 0xff; n >>>= 8;
  buf[1] = n & 0xff; n >>>= 8;
  buf[2] = n & 0xff; n >>>= 8;
  buf[3] = n & 0xff;
  return buf;
}

/** Decode a 4-byte little-endian Uint8Array to amountCents. */
function decodeAmountCents(bytes: Uint8Array): number {
  return (bytes[0] | (bytes[1] << 8) | (bytes[2] << 16) | (bytes[3] << 24)) >>> 0;
}

/**
 * IBE-encrypt an amountCents value to the homeowner's identity.
 *
 * @param pubKeyBytes  - Raw bytes from canister `getIbePublicKey()`.
 * @param homeownerPrincipalBytes - `principal.toUint8Array()` of the homeowner.
 * @param amountCents  - Bid amount in US cents.
 * @returns Serialized IbeCiphertext bytes to store in the canister.
 */
export async function ibeEncryptAmount(
  pubKeyBytes:             Uint8Array,
  homeownerPrincipalBytes: Uint8Array,
  amountCents:             number,
): Promise<Uint8Array> {
  const { DerivedPublicKey, IbeIdentity, IbeCiphertext, IbeSeed } =
    await import("@dfinity/vetkeys");
  const dpk      = DerivedPublicKey.deserialize(pubKeyBytes);
  const identity = IbeIdentity.fromBytes(homeownerPrincipalBytes);
  const plaintext = encodeAmountCents(amountCents);
  const ciphertext = IbeCiphertext.encrypt(dpk, identity, plaintext, IbeSeed.random());
  return ciphertext.serialize();
}

/**
 * Decrypt sealed bids using the homeowner's vetKey.
 *
 * @param encryptedKeyBytes  - `encryptedKey` from `revealBidsEncrypted()` canister call.
 * @param pubKeyBytes        - Raw bytes from `getIbePublicKey()`.
 * @param myPrincipalBytes   - `principal.toUint8Array()` of the homeowner (must match canister input).
 * @param tsk                - The TransportSecretKey whose public key was sent to the canister.
 * @param rawBids            - SealedBid records from the canister.
 * @returns Decrypted RevealedBid array with isWinner set for the lowest price.
 */
export async function ibeDecryptBids(
  encryptedKeyBytes:  Uint8Array,
  pubKeyBytes:        Uint8Array,
  myPrincipalBytes:   Uint8Array,
  tsk:                import("@dfinity/vetkeys").TransportSecretKey,
  rawBids: Array<{
    id:           string;
    requestId:    string;
    contractor:   string;   // principal text
    ciphertext:   number[];
    timelineDays: number;
    submittedAt:  bigint;
  }>,
): Promise<RevealedBid[]> {
  const { DerivedPublicKey, EncryptedVetKey, IbeCiphertext } =
    await import("@dfinity/vetkeys");

  const dpk         = DerivedPublicKey.deserialize(pubKeyBytes);
  const encVetKey   = EncryptedVetKey.deserialize(encryptedKeyBytes);
  const vetKey      = encVetKey.decryptAndVerify(tsk, dpk, myPrincipalBytes);

  const decoded = rawBids.map((b) => {
    const ct          = IbeCiphertext.deserialize(new Uint8Array(b.ciphertext));
    const plaintext   = ct.decrypt(vetKey);
    const amountCents = decodeAmountCents(plaintext);
    return { bid: b, amountCents };
  });

  const minAmount = decoded.length > 0 ? Math.min(...decoded.map((d) => d.amountCents)) : 0;

  return decoded.map(({ bid, amountCents }) => ({
    id:           bid.id,
    requestId:    bid.requestId,
    contractor:   bid.contractor,
    amountCents,
    timelineDays: bid.timelineDays,
    submittedAt:  Number(bid.submittedAt) / 1_000_000,
    isWinner:     amountCents === minAmount,
  }));
}
