/**
 * PropertyManagerClaimPage — /manage/claim/:token
 *
 * Publicly accessible page that lets an invited person claim a manager role
 * using the bearer token generated by the property owner.
 *
 * Flow:
 *  1. Page loads, looks up the manager invite by token (no auth needed).
 *  2. Unauthenticated visitor: sees property + role info + "Sign in to accept" button.
 *  3. Authenticated user: sees full details + "Accept [Role] Access" button.
 *  4. On claim: calls claimManagerRole(token) → redirects to /dashboard.
 */

import React, { useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { Loader2 } from "lucide-react";
import { propertyService, type ManagerInvite, type Property } from "../services/property";
import { useAuthStore } from "@/store/authStore";
import { COLORS, FONTS } from "@/theme";

const S = {
  ink:      COLORS.plum,
  paper:    COLORS.white,
  rule:     COLORS.rule,
  sage:     COLORS.sage,
  inkLight: COLORS.plumMid,
  mono:     FONTS.mono,
  serif:    FONTS.serif,
  sans:     FONTS.sans,
};

type PageState =
  | { status: "loading" }
  | { status: "not_found" }
  | { status: "expired" }
  | { status: "ready"; invite: ManagerInvite; property: Property | null }
  | { status: "claiming" }
  | { status: "claimed"; role: string; propertyId: bigint };

export default function PropertyManagerClaimPage() {
  const { token }   = useParams<{ token: string }>();
  const navigate    = useNavigate();
  const { isAuthenticated, isLoading: authLoading, principal } = useAuthStore();

  const [page, setPage]         = useState<PageState>({ status: "loading" });
  const [claimError, setClaimError] = useState<string | null>(null);

  // ── Load invite details ───────────────────────────────────────────────────

  useEffect(() => {
    if (!token) { setPage({ status: "not_found" }); return; }

    let cancelled = false;
    (async () => {
      try {
        const invite = await propertyService.getManagerInviteByToken(token);
        if (!invite) { if (!cancelled) setPage({ status: "not_found" }); return; }

        if (Date.now() > invite.expiresAt) {
          if (!cancelled) setPage({ status: "expired" });
          return;
        }

        let property: Property | null = null;
        try {
          property = await propertyService.getProperty(invite.propertyId);
        } catch { /* property details unavailable — degrade gracefully */ }

        if (!cancelled) setPage({ status: "ready", invite, property });
      } catch {
        if (!cancelled) setPage({ status: "not_found" });
      }
    })();
    return () => { cancelled = true; };
  }, [token]);

  // ── Claim handler ─────────────────────────────────────────────────────────

  async function handleClaim() {
    if (!token || page.status !== "ready") return;
    setPage({ status: "claiming" });
    setClaimError(null);
    try {
      const result = await propertyService.claimManagerRole(token);
      setPage({ status: "claimed", role: result.role, propertyId: result.propertyId });
      setTimeout(() => navigate("/dashboard"), 2000);
    } catch (e: any) {
      setClaimError(e.message ?? "Could not accept role. Please try again.");
      setPage(page);
    }
  }

  // ── Shared layout wrapper ─────────────────────────────────────────────────

  function Shell({ children }: { children: React.ReactNode }) {
    return (
      <div style={{
        minHeight: "100vh", background: S.paper,
        display: "flex", flexDirection: "column", alignItems: "center",
        justifyContent: "flex-start", padding: "4rem 1.5rem",
      }}>
        <Link to="/" style={{ textDecoration: "none", marginBottom: "2.5rem" }}>
          <span style={{ fontFamily: S.serif, fontWeight: 900, fontSize: "1.35rem", color: S.ink, letterSpacing: "-0.01em" }}>
            Home<span style={{ color: S.sage }}>Gentic</span>
          </span>
        </Link>
        <div style={{ width: "100%", maxWidth: "28rem", border: `1px solid ${S.rule}`, background: S.paper }}>
          {children}
        </div>
      </div>
    );
  }

  // ── Loading ───────────────────────────────────────────────────────────────

  if (page.status === "loading" || authLoading) {
    return (
      <Shell>
        <div style={{ padding: "2.5rem", display: "flex", flexDirection: "column", alignItems: "center", gap: "1rem" }}>
          <Loader2 size={20} color={S.inkLight} style={{ animation: "spin 1s linear infinite" }} />
          <span style={{ fontFamily: S.mono, fontSize: "0.65rem", color: S.inkLight, letterSpacing: "0.1em", textTransform: "uppercase" }}>
            Loading invite…
          </span>
        </div>
      </Shell>
    );
  }

  // ── Not found ─────────────────────────────────────────────────────────────

  if (page.status === "not_found") {
    return (
      <Shell>
        <div style={{ padding: "1.5rem 1.75rem", borderBottom: `1px solid ${S.rule}` }}>
          <p style={{ fontFamily: S.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: S.inkLight, marginBottom: "0.5rem" }}>Invite not found</p>
          <h1 style={{ fontFamily: S.serif, fontWeight: 900, fontSize: "1.5rem", color: S.ink, lineHeight: 1.2 }}>
            This link is no longer valid
          </h1>
        </div>
        <div style={{ padding: "1.5rem 1.75rem", display: "flex", flexDirection: "column", gap: "0.875rem" }}>
          <p style={{ fontFamily: S.sans, fontSize: "0.85rem", color: S.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
            The manager invite link could not be found. It may have already been used, or the URL may be incomplete.
          </p>
          <p style={{ fontFamily: S.sans, fontSize: "0.85rem", color: S.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
            Ask the property owner to generate a new invite link from their property settings.
          </p>
          <Link
            to="/"
            style={{ alignSelf: "flex-start", fontFamily: S.mono, fontSize: "0.6rem", letterSpacing: "0.1em", textTransform: "uppercase", padding: "0.5rem 1rem", background: S.ink, color: S.paper, textDecoration: "none", marginTop: "0.5rem" }}
          >
            Go to HomeGentic →
          </Link>
        </div>
      </Shell>
    );
  }

  // ── Expired ───────────────────────────────────────────────────────────────

  if (page.status === "expired") {
    return (
      <Shell>
        <div style={{ padding: "1.5rem 1.75rem", borderBottom: `1px solid ${S.rule}` }}>
          <p style={{ fontFamily: S.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: S.inkLight, marginBottom: "0.5rem" }}>Invite expired</p>
          <h1 style={{ fontFamily: S.serif, fontWeight: 900, fontSize: "1.5rem", color: S.ink, lineHeight: 1.2 }}>
            This link has expired
          </h1>
        </div>
        <div style={{ padding: "1.5rem 1.75rem" }}>
          <p style={{ fontFamily: S.sans, fontSize: "0.85rem", color: S.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
            Manager invite links are valid for 90 days. Ask the property owner to send a new invite link from their property settings.
          </p>
        </div>
      </Shell>
    );
  }

  // ── Claimed success ───────────────────────────────────────────────────────

  if (page.status === "claimed") {
    return (
      <Shell>
        <div style={{ padding: "1.5rem 1.75rem", borderBottom: `1px solid ${S.rule}`, background: COLORS.sageLight }}>
          <p style={{ fontFamily: S.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: S.sage, marginBottom: "0.5rem" }}>Access granted</p>
          <h1 style={{ fontFamily: S.serif, fontWeight: 900, fontSize: "1.5rem", color: S.ink, lineHeight: 1.2 }}>
            You're now a {page.role}
          </h1>
        </div>
        <div style={{ padding: "1.5rem 1.75rem" }}>
          <p style={{ fontFamily: S.sans, fontSize: "0.85rem", color: S.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
            {page.role === "Manager"
              ? "You can now view records, add maintenance jobs, upload photos, and manage this property on behalf of the owner."
              : "You can now view all records and history for this property."}
            {" "}Redirecting to your dashboard…
          </p>
        </div>
      </Shell>
    );
  }

  // ── Claiming in progress ──────────────────────────────────────────────────

  if (page.status === "claiming") {
    return (
      <Shell>
        <div style={{ padding: "2.5rem", display: "flex", flexDirection: "column", alignItems: "center", gap: "1rem" }}>
          <Loader2 size={20} color={S.inkLight} style={{ animation: "spin 1s linear infinite" }} />
          <span style={{ fontFamily: S.mono, fontSize: "0.65rem", color: S.inkLight, letterSpacing: "0.1em", textTransform: "uppercase" }}>
            Accepting role…
          </span>
        </div>
      </Shell>
    );
  }

  // ── Ready ─────────────────────────────────────────────────────────────────

  const { invite, property } = page;
  const expiresDate = new Date(invite.expiresAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });

  return (
    <Shell>
      {/* Header */}
      <div style={{ padding: "1.5rem 1.75rem", borderBottom: `1px solid ${S.rule}` }}>
        <p style={{ fontFamily: S.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: S.inkLight, marginBottom: "0.5rem" }}>
          Property access invitation
        </p>
        <h1 style={{ fontFamily: S.serif, fontWeight: 900, fontSize: "1.4rem", color: S.ink, lineHeight: 1.2, marginBottom: "0.5rem" }}>
          You've been invited as a {invite.role}
        </h1>
        <p style={{ fontFamily: S.mono, fontSize: "0.65rem", color: S.inkLight }}>
          Expires {expiresDate}
        </p>
      </div>

      {/* Invite details */}
      <div style={{ borderBottom: `1px solid ${S.rule}` }}>
        {[
          { label: "Invited As",  value: invite.displayName },
          { label: "Role",        value: invite.role },
          ...(property ? [
            { label: "Property",  value: property.address },
            { label: "City",      value: `${property.city}, ${property.state} ${property.zipCode}` },
          ] : [
            { label: "Property",  value: `#${String(invite.propertyId)}` },
          ]),
        ].map((row, i, arr) => (
          <div
            key={row.label}
            style={{
              display: "flex", justifyContent: "space-between", alignItems: "baseline",
              padding: "0.6rem 1.75rem",
              borderBottom: i < arr.length - 1 ? `1px solid ${S.rule}` : "none",
            }}
          >
            <span style={{ fontFamily: S.mono, fontSize: "0.55rem", letterSpacing: "0.1em", textTransform: "uppercase", color: S.inkLight }}>{row.label}</span>
            <span style={{ fontFamily: S.mono, fontSize: "0.7rem", color: S.ink }}>{row.value}</span>
          </div>
        ))}
      </div>

      {/* What this role grants */}
      <div style={{ padding: "1rem 1.75rem", borderBottom: `1px solid ${S.rule}`, background: COLORS.sageLight }}>
        <p style={{ fontFamily: S.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: S.sage, marginBottom: "0.5rem" }}>
          What {invite.role === "Manager" ? "Managers" : "Viewers"} can do
        </p>
        {(invite.role === "Manager"
          ? ["View all maintenance & job history", "Add maintenance jobs and notes", "Upload photos", "View utility bill records", "View room & fixture inventory"]
          : ["View all maintenance & job history", "View uploaded photos", "View utility bill records", "View room & fixture inventory"]
        ).map((item) => (
          <p key={item} style={{ fontFamily: S.sans, fontSize: "0.78rem", color: S.ink, lineHeight: 1.7, fontWeight: 300 }}>
            ✓ {item}
          </p>
        ))}
      </div>

      {/* Auth / accept action */}
      <div style={{ padding: "1.5rem 1.75rem", display: "flex", flexDirection: "column", gap: "0.875rem" }}>
        {!isAuthenticated ? (
          <>
            <p style={{ fontFamily: S.sans, fontSize: "0.82rem", color: S.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
              Sign in or create a free account to accept this invitation. The link will still work after you log in.
            </p>
            <Link
              to={`/login?redirect=${encodeURIComponent(`/manage/claim/${token}`)}`}
              style={{
                display: "block", textAlign: "center",
                fontFamily: S.mono, fontSize: "0.65rem", letterSpacing: "0.1em", textTransform: "uppercase",
                padding: "0.75rem 1rem", background: S.ink, color: S.paper, textDecoration: "none",
              }}
            >
              Sign in to accept →
            </Link>
          </>
        ) : (
          <>
            <p style={{ fontFamily: S.mono, fontSize: "0.6rem", color: S.inkLight, lineHeight: 1.5, wordBreak: "break-all" }}>
              Accepting as: <span style={{ color: S.ink }}>{principal}</span>
            </p>
            {claimError && (
              <p style={{ fontFamily: S.mono, fontSize: "0.65rem", color: S.inkLight }}>{claimError}</p>
            )}
            <button
              onClick={handleClaim}
              style={{
                fontFamily: S.mono, fontSize: "0.65rem", letterSpacing: "0.1em", textTransform: "uppercase",
                padding: "0.75rem 1rem", background: S.sage, color: S.paper, border: "none", cursor: "pointer",
              }}
            >
              Accept {invite.role} Access →
            </button>
            <p style={{ fontFamily: S.mono, fontSize: "0.55rem", color: S.inkLight, lineHeight: 1.5 }}>
              The property owner will be notified when you take significant actions.
            </p>
          </>
        )}
      </div>
    </Shell>
  );
}
