/**
 * PropertyTransferClaimPage — /transfer/claim/:token
 *
 * Publicly accessible page that lets a property buyer claim ownership using
 * the bearer token generated by the seller on PropertyDetailPage.
 *
 * Flow:
 *  1. Page loads, looks up the pending transfer by token (no auth needed).
 *  2. Unauthenticated visitor: sees property address + "Sign in to claim" button.
 *  3. Authenticated user: sees full property details + "Accept & Become Owner" button.
 *  4. On claim: calls claimTransfer(token) → redirects to /properties/:id.
 */

import React, { useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { Loader2 } from "lucide-react";
import { propertyService, type PendingTransfer, type Property } from "../services/property";
import { useAuthStore } from "@/store/authStore";
import { COLORS, FONTS } from "@/theme";

const UI = {
  ink:      COLORS.plum,
  paper:    COLORS.white,
  rule:     COLORS.rule,
  sage:     COLORS.sage,
  inkLight: COLORS.plumMid,
  rust:     COLORS.sage,    // primary action colour follows sage in this design
  mono:     FONTS.mono,
  serif:    FONTS.serif,
  sans:     FONTS.sans,
};

type PageState =
  | { status: "loading" }
  | { status: "not_found" }
  | { status: "expired" }
  | { status: "ready"; pending: PendingTransfer; property: Property }
  | { status: "claiming" }
  | { status: "claimed"; property: Property };

export default function PropertyTransferClaimPage() {
  const { token }   = useParams<{ token: string }>();
  const navigate    = useNavigate();
  const { isAuthenticated, isLoading: authLoading, principal } = useAuthStore();

  const [page, setPage]   = useState<PageState>({ status: "loading" });
  const [claimError, setClaimError] = useState<string | null>(null);

  // ── Load pending transfer details ─────────────────────────────────────────

  useEffect(() => {
    if (!token) { setPage({ status: "not_found" }); return; }

    let cancelled = false;
    (async () => {
      try {
        const pt = await propertyService.getPendingTransferByToken(token);
        if (!pt) { if (!cancelled) setPage({ status: "not_found" }); return; }

        if (Date.now() > pt.expiresAt) {
          if (!cancelled) setPage({ status: "expired" });
          return;
        }

        // Fetch property details — getProperty is an unauthenticated query
        try {
          const prop = await propertyService.getProperty(pt.propertyId);
          if (!cancelled) setPage({ status: "ready", pending: pt, property: prop });
        } catch {
          // Property details unavailable — still show enough to proceed
          if (!cancelled) setPage({ status: "ready", pending: pt, property: null as any });
        }
      } catch {
        if (!cancelled) setPage({ status: "not_found" });
      }
    })();
    return () => { cancelled = true; };
  }, [token]);

  // ── Claim handler ─────────────────────────────────────────────────────────

  async function handleClaim() {
    if (!token || page.status !== "ready") return;
    setPage({ status: "claiming" });
    setClaimError(null);
    try {
      const claimed = await propertyService.claimTransfer(token);
      setPage({ status: "claimed", property: claimed });
      // Brief pause so the success message registers, then navigate
      setTimeout(() => navigate(`/properties/${claimed.id}`), 1800);
    } catch (e: any) {
      setClaimError(e.message ?? "Claim failed. Please try again.");
      setPage(page);  // restore previous state so retry is available
    }
  }

  // ── Shared layout wrapper ─────────────────────────────────────────────────

  function Shell({ children }: { children: React.ReactNode }) {
    return (
      <div style={{
        minHeight: "100vh", background: UI.paper,
        display: "flex", flexDirection: "column", alignItems: "center",
        justifyContent: "flex-start", padding: "4rem 1.5rem",
      }}>
        {/* Wordmark */}
        <Link to="/" style={{ textDecoration: "none", marginBottom: "2.5rem" }}>
          <span style={{ fontFamily: UI.serif, fontWeight: 900, fontSize: "1.35rem", color: UI.ink, letterSpacing: "-0.01em" }}>
            Home<span style={{ color: UI.sage, fontStyle: "italic", fontWeight: 300 }}>Gentic</span>
          </span>
        </Link>

        <div style={{
          width: "100%", maxWidth: "28rem",
          border: `1px solid ${UI.rule}`, background: UI.paper,
        }}>
          {children}
        </div>
      </div>
    );
  }

  // ── Loading ───────────────────────────────────────────────────────────────

  if (page.status === "loading" || authLoading) {
    return (
      <Shell>
        <div style={{ padding: "2.5rem", display: "flex", flexDirection: "column", alignItems: "center", gap: "1rem" }}>
          <Loader2 size={20} color={UI.inkLight} style={{ animation: "spin 1s linear infinite" }} />
          <span style={{ fontFamily: UI.mono, fontSize: "0.65rem", color: UI.inkLight, letterSpacing: "0.1em", textTransform: "uppercase" }}>
            Loading transfer…
          </span>
        </div>
      </Shell>
    );
  }

  // ── Not found ─────────────────────────────────────────────────────────────

  if (page.status === "not_found") {
    return (
      <Shell>
        <div style={{ padding: "1.5rem 1.75rem", borderBottom: `1px solid ${UI.rule}` }}>
          <p style={{ fontFamily: UI.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: UI.inkLight, marginBottom: "0.5rem" }}>Transfer not found</p>
          <h1 style={{ fontFamily: UI.serif, fontWeight: 900, fontSize: "1.5rem", color: UI.ink, lineHeight: 1.2 }}>
            This link is no longer valid
          </h1>
        </div>
        <div style={{ padding: "1.5rem 1.75rem", display: "flex", flexDirection: "column", gap: "0.875rem" }}>
          <p style={{ fontFamily: UI.sans, fontSize: "0.85rem", color: UI.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
            The transfer link could not be found. It may have already been used, cancelled by the seller, or the URL may be incomplete.
          </p>
          <p style={{ fontFamily: UI.sans, fontSize: "0.85rem", color: UI.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
            Ask the seller to generate a new transfer link from their property settings.
          </p>
          <Link
            to="/"
            style={{ alignSelf: "flex-start", fontFamily: UI.mono, fontSize: "0.6rem", letterSpacing: "0.1em", textTransform: "uppercase", padding: "0.5rem 1rem", background: UI.ink, color: UI.paper, textDecoration: "none", marginTop: "0.5rem" }}
          >
            Go to HomeGentic →
          </Link>
        </div>
      </Shell>
    );
  }

  // ── Expired ───────────────────────────────────────────────────────────────

  if (page.status === "expired") {
    return (
      <Shell>
        <div style={{ padding: "1.5rem 1.75rem", borderBottom: `1px solid ${UI.rule}` }}>
          <p style={{ fontFamily: UI.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: UI.inkLight, marginBottom: "0.5rem" }}>Transfer expired</p>
          <h1 style={{ fontFamily: UI.serif, fontWeight: 900, fontSize: "1.5rem", color: UI.ink, lineHeight: 1.2 }}>
            This link has expired
          </h1>
        </div>
        <div style={{ padding: "1.5rem 1.75rem" }}>
          <p style={{ fontFamily: UI.sans, fontSize: "0.85rem", color: UI.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
            Property transfer links are valid for 90 days. This one has passed its expiry date. Ask the seller to generate a new link from their property settings.
          </p>
        </div>
      </Shell>
    );
  }

  // ── Claimed success ───────────────────────────────────────────────────────

  if (page.status === "claimed") {
    return (
      <Shell>
        <div style={{ padding: "1.5rem 1.75rem", borderBottom: `1px solid ${UI.rule}`, background: COLORS.sageLight }}>
          <p style={{ fontFamily: UI.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: UI.sage, marginBottom: "0.5rem" }}>Transfer complete</p>
          <h1 style={{ fontFamily: UI.serif, fontWeight: 900, fontSize: "1.5rem", color: UI.ink, lineHeight: 1.2 }}>
            You're the new owner
          </h1>
        </div>
        <div style={{ padding: "1.5rem 1.75rem" }}>
          <p style={{ fontFamily: UI.sans, fontSize: "0.85rem", color: UI.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
            The full property history — maintenance records, photos, utility bills, and verification status — is now in your account. Redirecting you to the property…
          </p>
        </div>
      </Shell>
    );
  }

  // ── Claiming in progress ──────────────────────────────────────────────────

  if (page.status === "claiming") {
    return (
      <Shell>
        <div style={{ padding: "2.5rem", display: "flex", flexDirection: "column", alignItems: "center", gap: "1rem" }}>
          <Loader2 size={20} color={UI.inkLight} style={{ animation: "spin 1s linear infinite" }} />
          <span style={{ fontFamily: UI.mono, fontSize: "0.65rem", color: UI.inkLight, letterSpacing: "0.1em", textTransform: "uppercase" }}>
            Transferring ownership on-chain…
          </span>
        </div>
      </Shell>
    );
  }

  // ── Ready — show property details and claim UI ────────────────────────────

  const { pending, property } = page;
  const expiresDate = new Date(pending.expiresAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
  const propertyLabel = property
    ? `${property.address}, ${property.city} ${property.state} ${property.zipCode}`
    : `Property #${String(pending.propertyId)}`;

  return (
    <Shell>
      {/* Header */}
      <div style={{ padding: "1.5rem 1.75rem", borderBottom: `1px solid ${UI.rule}` }}>
        <p style={{ fontFamily: UI.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: UI.inkLight, marginBottom: "0.5rem" }}>
          Property ownership transfer
        </p>
        <h1 style={{ fontFamily: UI.serif, fontWeight: 900, fontSize: "1.4rem", color: UI.ink, lineHeight: 1.2, marginBottom: "0.5rem" }}>
          Claim this property
        </h1>
        <p style={{ fontFamily: UI.mono, fontSize: "0.65rem", color: UI.inkLight }}>
          Expires {expiresDate}
        </p>
      </div>

      {/* Property details */}
      <div style={{ borderBottom: `1px solid ${UI.rule}` }}>
        {property ? (
          <>
            {[
              { label: "Address",      value: property.address },
              { label: "City",         value: `${property.city}, ${property.state} ${property.zipCode}` },
              { label: "Type",         value: property.propertyType },
              { label: "Year Built",   value: String(property.yearBuilt) },
              { label: "Verification", value: property.verificationLevel },
            ].map((row, i, arr) => (
              <div
                key={row.label}
                style={{
                  display: "flex", justifyContent: "space-between", alignItems: "baseline",
                  padding: "0.6rem 1.75rem",
                  borderBottom: i < arr.length - 1 ? `1px solid ${UI.rule}` : "none",
                }}
              >
                <span style={{ fontFamily: UI.mono, fontSize: "0.55rem", letterSpacing: "0.1em", textTransform: "uppercase", color: UI.inkLight }}>{row.label}</span>
                <span style={{ fontFamily: UI.mono, fontSize: "0.7rem", color: UI.ink }}>{row.value}</span>
              </div>
            ))}
          </>
        ) : (
          <div style={{ padding: "0.875rem 1.75rem" }}>
            <span style={{ fontFamily: UI.mono, fontSize: "0.7rem", color: UI.inkLight }}>{propertyLabel}</span>
          </div>
        )}
      </div>

      {/* What transfers */}
      <div style={{ padding: "1rem 1.75rem", borderBottom: `1px solid ${UI.rule}`, background: COLORS.sageLight }}>
        <p style={{ fontFamily: UI.mono, fontSize: "0.55rem", letterSpacing: "0.12em", textTransform: "uppercase", color: UI.sage, marginBottom: "0.5rem" }}>
          What you'll receive
        </p>
        {[
          "Full maintenance & job history",
          "All uploaded photos",
          "Utility bill records",
          "Verification status (Basic / Premium)",
          "Room & fixture inventory",
        ].map((item) => (
          <p key={item} style={{ fontFamily: UI.sans, fontSize: "0.78rem", color: UI.ink, lineHeight: 1.7, fontWeight: 300 }}>
            ✓ {item}
          </p>
        ))}
      </div>

      {/* Auth / claim action */}
      <div style={{ padding: "1.5rem 1.75rem", display: "flex", flexDirection: "column", gap: "0.875rem" }}>
        {!isAuthenticated ? (
          <>
            <p style={{ fontFamily: UI.sans, fontSize: "0.82rem", color: UI.inkLight, lineHeight: 1.6, fontWeight: 300 }}>
              Sign in or create a free account to claim this property. The link will still work after you log in.
            </p>
            <Link
              to={`/login?redirect=${encodeURIComponent(`/transfer/claim/${token}`)}`}
              style={{
                display: "block", textAlign: "center",
                fontFamily: UI.mono, fontSize: "0.65rem", letterSpacing: "0.1em", textTransform: "uppercase",
                padding: "0.75rem 1rem", background: UI.ink, color: UI.paper, textDecoration: "none",
              }}
            >
              Sign in to claim →
            </Link>
          </>
        ) : (
          <>
            <p style={{ fontFamily: UI.mono, fontSize: "0.6rem", color: UI.inkLight, lineHeight: 1.5, wordBreak: "break-all" }}>
              Claiming as: <span style={{ color: UI.ink }}>{principal}</span>
            </p>
            {claimError && (
              <p style={{ fontFamily: UI.mono, fontSize: "0.65rem", color: UI.rust }}>{claimError}</p>
            )}
            <button
              onClick={handleClaim}
              style={{
                fontFamily: UI.mono, fontSize: "0.65rem", letterSpacing: "0.1em", textTransform: "uppercase",
                padding: "0.75rem 1rem", background: UI.sage, color: UI.paper, border: "none", cursor: "pointer",
              }}
            >
              Accept &amp; Become Owner →
            </button>
            <p style={{ fontFamily: UI.mono, fontSize: "0.55rem", color: UI.inkLight, lineHeight: 1.5 }}>
              This action is recorded on-chain. The previous owner's access is immediately revoked.
            </p>
          </>
        )}
      </div>
    </Shell>
  );
}
